name: chronologe_poc
description: "PoC for Chronologe: Let your day write itself."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  hive_ce_flutter: ^2.3.4
  table_calendar: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
