import 'package:chronologe_poc/dbhelper.dart';

class SampleEntry {
  static Future<void> populateDatabase() async {
    List<Map> samples = [
      {
        'date': '2026-08-01',
        'left_home': '8:00 AM',
        'morning': 'Office commute',
        'afternoon': 'Project meetings',
        'evening': 'Walk in the park',
        'returned_home': '7:30 PM',
        'news': 'Technology summit announced',
        'mood': 'Tired',
        'weather': 'Light rain',
        'temp': '23°C',
        'title': 'Tired Moments',
        'text':
            "I left home at 8:00 AM and spent the morning on my office commute under light rain and 23°C weather. The afternoon was filled with project meetings before I took a quiet walk in the park. I returned home at 7:30 PM after hearing about a newly announced technology summit, ending the day feeling tired.",
      },
      {
        'date': '2026-08-02',
        'left_home': '9:00 AM',
        'morning': 'Breakfast with family',
        'afternoon': 'Movie',
        'evening': 'Dinner outside',
        'returned_home': '9:30 PM',
        'news': 'New science museum opened',
        'mood': 'Calm',
        'weather': 'Cloudy',
        'temp': '24°C',
        'title': 'A Quiet Sunday',
        'text':
            "I left home at 9:00 AM for breakfast with my family while the sky stayed cloudy and cool at 24°C. We watched a movie in the afternoon and went out for dinner later. I returned home at 9:30 PM feeling calm, with the opening of a new science museum being the most interesting news of the day.",
      },
      {
        'date': '2026-08-03',
        'left_home': '7:45 AM',
        'morning': 'College classes',
        'afternoon': 'Library study',
        'evening': 'Gaming',
        'returned_home': '6:45 PM',
        'news': 'Local university announced new courses',
        'mood': 'Calm',
        'weather': 'Sunny',
        'temp': '28°C',
        'title': 'Study and Recharge',
        'text':
            "I left home at 7:45 AM on a sunny 28°C morning and spent the first part of the day attending college classes. The afternoon was quieter as I studied in the library, and I relaxed with some gaming after returning home at 6:45 PM. News about new university courses made the day feel productive and calm.",
      },
      {
        'date': '2026-08-04',
        'left_home': '8:30 AM',
        'morning': 'Work from cafe',
        'afternoon': 'Shopping',
        'evening': 'Visited family',
        'returned_home': '8:00 PM',
        'news': 'New shopping complex approved',
        'mood': 'Reflective',
        'weather': 'Cloudy',
        'temp': '25°C',
        'title': 'A Change of Pace',
        'text':
            "I left home at 8:30 AM and worked from a cafe while the cloudy 25°C weather made the morning feel relaxed. I spent the afternoon shopping and visited family in the evening before returning home at 8:00 PM. Hearing about a new shopping complex left me reflecting on how quickly the city keeps changing.",
      },
      {
        'date': '2026-08-05',
        'left_home': '7:30 AM',
        'morning': 'Office commute',
        'afternoon': 'Office work',
        'evening': 'Gym',
        'returned_home': '8:15 PM',
        'news': 'Metro services expanded',
        'mood': 'Tired',
        'weather': 'Breezy',
        'temp': '24°C',
        'title': 'A Long Workday',
        'text':
            "I left home at 7:30 AM in breezy 24°C weather and made my usual commute to the office. Most of the afternoon was spent working, followed by a gym session in the evening. I finally returned home at 8:15 PM tired but satisfied, while expanded metro services were the main local news.",
      },
      {
        'date': '2026-08-06',
        'left_home': '10:00 AM',
        'morning': 'Coffee shop',
        'afternoon': 'Reading',
        'evening': 'Cooked dinner',
        'returned_home': '5:30 PM',
        'news': 'Book fair announced',
        'mood': 'Reflective',
        'weather': 'Cloudy',
        'temp': '22°C',
        'title': 'A Slow Afternoon',
        'text':
            "I left home at 10:00 AM and spent a cloudy 22°C morning at a coffee shop. The afternoon passed quietly with a book, and after coming home at 5:30 PM I cooked dinner. News of an upcoming book fair matched the slow pace of the day and left me feeling reflective.",
      },
      {
        'date': '2026-08-07',
        'left_home': '8:00 AM',
        'morning': 'Office work',
        'afternoon': 'Client meeting',
        'evening': 'Takeaway dinner',
        'returned_home': '9:00 PM',
        'news': 'Heat advisory issued',
        'mood': 'Tired',
        'weather': 'Hot',
        'temp': '34°C',
        'title': 'Through the Heat',
        'text':
            "I left home at 8:00 AM with the temperature already climbing toward 34°C. Office work took up the morning and a client meeting filled most of the afternoon, leaving me ready for an easy takeaway dinner. I returned home at 9:00 PM tired, and the day's heat advisory certainly felt justified.",
      },
      {
        'date': '2026-08-08',
        'left_home': '11:00 AM',
        'morning': 'Brunch',
        'afternoon': 'Shopping',
        'evening': 'Concert',
        'returned_home': '11:30 PM',
        'news': 'Music festival announced',
        'mood': 'Excited',
        'weather': 'Cloudy',
        'temp': '26°C',
        'title': 'Music and Energy',
        'text':
            "I left home at 11:00 AM for brunch beneath cloudy skies and comfortable 26°C weather. Shopping filled the afternoon before I headed to a concert in the evening. I returned home at 11:30 PM still excited, especially after hearing that another music festival had just been announced.",
      },
      {
        'date': '2026-08-09',
        'left_home': '9:30 AM',
        'morning': 'Park walk',
        'afternoon': 'Lunch with friends',
        'evening': 'Watched a movie',
        'returned_home': '7:00 PM',
        'news': 'City park renovation completed',
        'mood': 'Tired',
        'weather': 'Sunny',
        'temp': '30°C',
        'title': 'Sunday Outdoors',
        'text':
            "I left home at 9:30 AM for a walk in the park under sunny 30°C skies. Lunch with friends made for a lively afternoon, and I finished the day with a movie after returning home at 7:00 PM. The renovated city park looked great, although I was tired by the end of the day.",
      },
      {
        'date': '2026-08-10',
        'left_home': '8:15 AM',
        'morning': 'College classes',
        'afternoon': 'Group project',
        'evening': 'Reading',
        'returned_home': '6:30 PM',
        'news': 'New research centre announced',
        'mood': 'Reflective',
        'weather': 'Cloudy',
        'temp': '24°C',
        'title': 'Ideas Taking Shape',
        'text':
            "I left home at 8:15 AM in cloudy 24°C weather for a morning of classes. My afternoon was spent working with the group on our project, and I relaxed with some reading after returning at 6:30 PM. News of a new research centre made me think about where my own studies might eventually lead.",
      },
      {
        'date': '2026-08-11',
        'left_home': '8:00 AM',
        'morning': 'Office work',
        'afternoon': 'Presentation',
        'evening': 'Dinner with friends',
        'returned_home': '9:00 PM',
        'news': 'Startup funding increased',
        'mood': 'Reflective',
        'weather': 'Sunny',
        'temp': '29°C',
        'title': 'Presentations and Possibilities',
        'text':
            "I left home at 8:00 AM under sunny 29°C skies and spent the morning working at the office. A presentation occupied the afternoon, followed by dinner with friends before I returned at 9:00 PM. News about increased startup funding gave me plenty to think about on the way home.",
      },
      {
        'date': '2026-08-12',
        'left_home': '9:00 AM',
        'morning': 'Cafe breakfast',
        'afternoon': 'Museum visit',
        'evening': 'Walk',
        'returned_home': '7:15 PM',
        'news': 'Art exhibition opened',
        'mood': 'Calm',
        'weather': 'Sunny',
        'temp': '27°C',
        'title': 'An Easy Day Out',
        'text':
            "I started the day at 9:00 AM with breakfast at a cafe under clear 27°C skies. A museum visit filled the afternoon, and I took a relaxed evening walk before reaching home at 7:15 PM. The opening of a new art exhibition seemed fitting for such a calm day.",
      },
      {
        'date': '2026-08-13',
        'left_home': '7:50 AM',
        'morning': 'Office commute',
        'afternoon': 'Office work',
        'evening': 'Stayed indoors',
        'returned_home': '6:45 PM',
        'news': 'Heavy rain warning issued',
        'mood': 'Calm',
        'weather': 'Light rain',
        'temp': '22°C',
        'title': 'Rain Against the Window',
        'text':
            "I left home at 7:50 AM as light rain fell and the temperature stayed around 22°C. The day was mostly ordinary office work, and after getting home at 6:45 PM I chose to stay indoors. A heavier rain warning was issued later, making the quiet evening feel especially comfortable.",
      },
      {
        'date': '2026-08-14',
        'left_home': '8:20 AM',
        'morning': 'Classes',
        'afternoon': 'Assignment work',
        'evening': 'Coffee with friend',
        'returned_home': '8:00 PM',
        'news': 'Education policy update announced',
        'mood': 'Reflective',
        'weather': 'Light rain',
        'temp': '23°C',
        'title': 'Questions and Coffee',
        'text':
            "I left home at 8:20 AM during light rain and spent the morning in class. Assignment work occupied the afternoon before I met a friend for coffee in the evening. I got home at 8:00 PM feeling reflective, with the day's education policy announcement giving me even more to think about.",
      },
      {
        'date': '2026-08-15',
        'left_home': '10:00 AM',
        'morning': 'Holiday breakfast',
        'afternoon': 'Family gathering',
        'evening': 'Dinner',
        'returned_home': '10:00 PM',
        'news': 'Independence Day celebrations held',
        'mood': 'Excited',
        'weather': 'Light rain',
        'temp': '24°C',
        'title': 'A Day of Celebration',
        'text':
            "I left home at 10:00 AM after a relaxed holiday breakfast while light rain kept the temperature near 24°C. The afternoon was spent with family, followed by a long dinner together. I returned at 10:00 PM feeling excited after a day filled with Independence Day celebrations across the city.",
      },
      {
        'date': '2026-08-16',
        'left_home': '9:30 AM',
        'morning': 'Shopping',
        'afternoon': 'Lunch',
        'evening': 'Gaming',
        'returned_home': '5:00 PM',
        'news': 'Weekend market attracted record visitors',
        'mood': 'Reflective',
        'weather': 'Hot',
        'temp': '32°C',
        'title': 'A Warm Sunday',
        'text':
            "I left home at 9:30 AM for some shopping on a hot 32°C morning. Lunch outside rounded off the afternoon before I returned home at 5:00 PM and spent the evening gaming. The crowded weekend market made me appreciate how nice it was to finally have a quiet evening.",
      },
      {
        'date': '2026-08-17',
        'left_home': '7:30 AM',
        'morning': 'Office commute',
        'afternoon': 'Deadline work',
        'evening': 'Gym',
        'returned_home': '9:00 PM',
        'news': 'Major company announced expansion',
        'mood': 'Tired',
        'weather': 'Hot',
        'temp': '33°C',
        'title': 'Deadline Monday',
        'text':
            "I left home at 7:30 AM in hot 33°C weather and headed straight into a busy workday. Most of the afternoon was spent racing against a deadline before I managed a short gym session. I reached home at 9:00 PM exhausted, with news of a major company expansion barely registering after such a long day.",
      },
      {
        'date': '2026-08-18',
        'left_home': '8:30 AM',
        'morning': 'Breakfast meeting',
        'afternoon': 'Project work',
        'evening': 'Dinner with family',
        'returned_home': '8:30 PM',
        'news': 'New public park proposed',
        'mood': 'Happy',
        'weather': 'Hot',
        'temp': '31°C',
        'title': 'A Productive Tuesday',
        'text':
            "I left home at 8:30 AM for a breakfast meeting while the day warmed to 31°C. Project work went smoothly through the afternoon, and dinner with my family made for a pleasant ending. I returned at 8:30 PM feeling happy, especially after hearing plans for a new public park.",
      },
      {
        'date': '2026-08-19',
        'left_home': '8:00 AM',
        'morning': 'College classes',
        'afternoon': 'Lab session',
        'evening': 'Stayed home',
        'returned_home': '6:00 PM',
        'news': 'Rainfall improved reservoir levels',
        'mood': 'Calm',
        'weather': 'Light rain',
        'temp': '22°C',
        'title': 'A Cool Study Day',
        'text':
            "I left home at 8:00 AM as light rain cooled the morning to 22°C. Classes and a lab session kept me occupied through the afternoon, and I returned home at 6:00 PM for a quiet evening. News that the rain had improved reservoir levels added a reassuring end to the day.",
      },
      {
        'date': '2026-08-20',
        'left_home': '9:00 AM',
        'morning': 'Work from cafe',
        'afternoon': 'Project planning',
        'evening': 'Bookstore visit',
        'returned_home': '7:30 PM',
        'news': 'New technology regulations proposed',
        'mood': 'Reflective',
        'weather': 'Light rain',
        'temp': '23°C',
        'title': 'Planning Ahead',
        'text':
            "I left home at 9:00 AM and worked from a cafe while light rain fell outside at 23°C. The afternoon was devoted to project planning, followed by a bookstore visit before I reached home at 7:30 PM. News about proposed technology regulations left me thinking about how quickly the industry is changing.",
      },
      {
        'date': '2026-08-21',
        'left_home': '8:15 AM',
        'morning': 'Office work',
        'afternoon': 'Team meeting',
        'evening': 'Walk',
        'returned_home': '7:00 PM',
        'news': 'City announced new cycling lanes',
        'mood': 'Reflective',
        'weather': 'Hot',
        'temp': '31°C',
        'title': 'Thinking on the Walk Home',
        'text':
            "I left home at 8:15 AM on a hot 31°C morning and spent most of the day at the office. A long team meeting filled the afternoon, and I took a walk after work before arriving home at 7:00 PM. News about new cycling lanes made me reflect on how the city might become easier to move around.",
      },
      {
        'date': '2026-08-22',
        'left_home': '11:00 AM',
        'morning': 'Brunch',
        'afternoon': 'Arcade',
        'evening': 'Dinner with friends',
        'returned_home': '10:30 PM',
        'news': 'Gaming convention announced',
        'mood': 'Excited',
        'weather': 'Hot',
        'temp': '32°C',
        'title': 'Games and Good Company',
        'text':
            "I left home at 11:00 AM for brunch despite the hot 32°C weather. The afternoon disappeared quickly at an arcade, followed by dinner with friends in the evening. I returned home at 10:30 PM excited, and news of an upcoming gaming convention made the day even better.",
      },
      {
        'date': '2026-08-23',
        'left_home': '8:30 AM',
        'morning': 'Cycling',
        'afternoon': 'Lunch at home',
        'evening': 'Movie',
        'returned_home': '11:00 AM',
        'news': 'New nature trail opened',
        'mood': 'Calm',
        'weather': 'Breezy',
        'temp': '24°C',
        'title': 'A Breezy Morning',
        'text':
            "I left home at 8:30 AM for a cycling session in breezy 24°C weather and returned before lunch. The rest of the afternoon was quiet at home, and I finished the evening with a movie. Hearing about a newly opened nature trail made me want to plan another peaceful ride soon.",
      },
      {
        'date': '2026-08-24',
        'left_home': '7:45 AM',
        'morning': 'Office commute',
        'afternoon': 'Office work',
        'evening': 'Grocery shopping',
        'returned_home': '8:00 PM',
        'news': 'Public transport fares revised',
        'mood': 'Excited',
        'weather': 'Cloudy',
        'temp': '25°C',
        'title': 'A Busy Start to the Week',
        'text':
            "I left home at 7:45 AM beneath cloudy 25°C skies and headed to the office. Work kept me occupied all afternoon, followed by grocery shopping before I reached home at 8:00 PM. The revised public transport fares were the main news of the day, and despite the busy schedule I ended it feeling surprisingly excited.",
      },
      {
        'date': '2026-08-25',
        'left_home': '8:00 AM',
        'morning': 'Classes',
        'afternoon': 'Project demonstration',
        'evening': 'Dinner outside',
        'returned_home': '9:00 PM',
        'news': 'Student innovation event announced',
        'mood': 'Happy',
        'weather': 'Light rain',
        'temp': '23°C',
        'title': 'A Successful Demo',
        'text':
            "I left home at 8:00 AM while light rain kept the temperature near 23°C. After morning classes, I spent the afternoon presenting a project demonstration that went better than expected. Dinner outside followed, and I arrived home at 9:00 PM happy, just as a new student innovation event was being announced.",
      },
      {
        'date': '2026-08-26',
        'left_home': '9:00 AM',
        'morning': 'Coffee and planning',
        'afternoon': 'Coding',
        'evening': 'Music',
        'returned_home': '6:30 PM',
        'news': 'Open-source conference announced',
        'mood': 'Happy',
        'weather': 'Hot',
        'temp': '30°C',
        'title': 'Code and Coffee',
        'text':
            "I left home at 9:00 AM for coffee and some planning while the temperature reached 30°C. I spent the afternoon coding and made good progress before returning at 6:30 PM. Music filled the evening, and news of an upcoming open-source conference gave me another reason to end the day happy.",
      },
      {
        'date': '2026-08-27',
        'left_home': '8:30 AM',
        'morning': 'Visited a cafe',
        'afternoon': 'Shopping',
        'evening': 'Visited family',
        'returned_home': '8:00 PM',
        'news': 'India won a cricket match',
        'mood': 'Reflective',
        'weather': 'Sunny',
        'temp': '29°C',
        'title': 'Reflective Moments',
        'text':
            "I left home at 8:30 AM and spent the morning at a cafe under sunny 29°C skies. My afternoon was centred around shopping, followed by visiting family in the evening before I returned home at 8:00 PM. India winning a cricket match was the day's big news, and I ended the day feeling reflective about how it had unfolded.",
      },
      {
        'date': '2026-08-28',
        'left_home': '7:50 AM',
        'morning': 'Office commute',
        'afternoon': 'Finished weekly tasks',
        'evening': 'Dinner with coworkers',
        'returned_home': '9:15 PM',
        'news': 'Technology company launched new product',
        'mood': 'Calm',
        'weather': 'Sunny',
        'temp': '28°C',
        'title': 'A Smooth Friday',
        'text':
            "I left home at 7:50 AM under sunny 28°C skies for the final workday of the week. I wrapped up my remaining tasks during the afternoon and went to dinner with coworkers afterward. I returned home at 9:15 PM feeling calm, while a major new technology launch dominated the day's news.",
      },
      {
        'date': '2026-08-29',
        'left_home': '10:00 AM',
        'morning': 'Breakfast outside',
        'afternoon': 'Park visit',
        'evening': 'Cooking',
        'returned_home': '5:00 PM',
        'news': 'Weekend cultural festival opened',
        'mood': 'Tired',
        'weather': 'Breezy',
        'temp': '25°C',
        'title': 'A Breezy Saturday',
        'text':
            "I left home at 10:00 AM for breakfast outside while a pleasant breeze kept the temperature around 25°C. I visited the park during the afternoon and returned home at 5:00 PM to cook dinner. A cultural festival had opened nearby, but after the day's walking I was happy to stay home and rest.",
      },
      {
        'date': '2026-08-30',
        'left_home': '9:30 AM',
        'morning': 'Family breakfast',
        'afternoon': 'Housework',
        'evening': 'Short walk',
        'returned_home': '6:00 PM',
        'news': 'New community centre inaugurated',
        'mood': 'Tired',
        'weather': 'Hot',
        'temp': '32°C',
        'title': 'A Simple Sunday',
        'text':
            "I left home at 9:30 AM for breakfast with family on a hot 32°C morning. Most of the afternoon was spent doing housework, followed by a short walk before I settled back home around 6:00 PM. News of a new community centre was encouraging, though I ended the day feeling tired.",
      },
      {
        'date': '2026-08-31',
        'left_home': '8:00 AM',
        'morning': 'Office work',
        'afternoon': 'Monthly review',
        'evening': 'Dinner at home',
        'returned_home': '7:00 PM',
        'news': 'Economic report showed steady growth',
        'mood': 'Happy',
        'weather': 'Sunny',
        'temp': '29°C',
        'title': 'Ending August Well',
        'text':
            "I left home at 8:00 AM beneath sunny 29°C skies and began the week at the office. A monthly review filled much of the afternoon, giving me a chance to look back at everything accomplished during August. I returned home at 7:00 PM for dinner, ending the month happy as the day's economic report showed steady growth.",
      },
    ];

    // Add every sample to the database
    for (Map sample in samples) {
      String date = sample['date'];

      // Do not overwrite an entry that already exists
      if (DBHelper.readEntry(date) == null) {
        await DBHelper.changeTitle(
          date,
          sample['title'],
        );

        await DBHelper.changeText(
          date,
          sample['text'],
        );

        await DBHelper.changeMood(
          date,
          sample['mood'],
        );

        await DBHelper.changeWeather(
          date,
          sample['weather'],
          sample['temp'],
        );
      }
    }
  }
}